# Generated by Django 5.0 on 2023-12-20 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 20, 18, 59, 12, 504601), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 20, 18, 59, 12, 505599), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(max_length=255),
        ),
    ]
