# Generated by Django 5.0 on 2023-12-21 11:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_order_cart_order_products_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 21, 14, 35, 17, 271124), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 21, 14, 35, 17, 271124), verbose_name='Дата комментария'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('quantity', models.PositiveIntegerField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
