# Generated by Django 5.0 on 2023-12-25 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_blog_posted_alter_comment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Заказ создан"),
                    ("ready", "Готов к выдаче"),
                    ("canceled", "Отменен"),
                ],
                default="created",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 12, 25, 19, 44, 52, 752345),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 12, 25, 19, 44, 52, 753347),
                verbose_name="Дата комментария",
            ),
        ),
    ]
