# Generated by Django 4.2.8 on 2023-12-25 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 25, 23, 46, 29, 82885), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 25, 23, 46, 29, 84236), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(),
        ),
    ]
