# Generated by Django 5.0 on 2024-04-29 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_order_address_order_email_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='product',
            name='floors',
            field=models.IntegerField(default=None, null=True, verbose_name='Этажи'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 29, 19, 36, 23, 614412), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 29, 19, 36, 23, 615409), verbose_name='Дата комментария'),
        ),
    ]
